name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build artifacts
      run: mvn clean package
    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run: |
          chmod +x ./scripts/InstallChrome.sh
          ./scripts/InstallChrome.sh 
    - name: Build with Maven
      run: mvn test --file pom.xml
    - name: Run testsigma Automation suite
      run: |
        chmod +x run_smoke_tests.sh.sh
        ./run_smoke_tests.sh
    - name: upload all test files
      uses: actions/upload-artifact@v2
      with:
        name: Test-files
        path: ./*
  
